//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.30 at 05:39:42 PM NZDT 
//


package talkbank.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for beginEndSimpleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="beginEndSimpleType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="begin"/>
 *     &lt;enumeration value="end"/>
 *     &lt;enumeration value="simple"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "beginEndSimpleType")
@XmlEnum
public enum BeginEndSimpleType {


    /**
     * Begin delimited material
     * 
     */
    @XmlEnumValue("begin")
    BEGIN("begin"),

    /**
     * End delimited material
     * 
     */
    @XmlEnumValue("end")
    END("end"),

    /**
     * 
     *                         Begin and end delimited material (degenerate case)
     *                     
     * 
     */
    @XmlEnumValue("simple")
    SIMPLE("simple");
    private final String value;

    BeginEndSimpleType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BeginEndSimpleType fromValue(String v) {
        for (BeginEndSimpleType c: BeginEndSimpleType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
