//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.30 at 05:39:42 PM NZDT 
//


package talkbank.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Metadata" type="{http://www.talkbank.org/ns/talkbank}Metadata" minOccurs="0"/>
 *         &lt;element name="Participants">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="participant" type="{http://www.talkbank.org/ns/talkbank}participantType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}comment"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}tcu"/>
 *           &lt;element name="begin-gem">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;attribute name="label" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="end-gem">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;attribute name="label" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="lazy-gem">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;attribute name="label" use="required" type="{http://www.talkbank.org/ns/talkbank}nonemptyStringType" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}u"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="Id" use="required" type="{http://www.talkbank.org/ns/talkbank}nonemptyStringType" />
 *       &lt;attribute name="Version" use="required" type="{http://www.talkbank.org/ns/talkbank}nonemptyStringType" />
 *       &lt;attribute name="Date" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="Corpus" use="required" type="{http://www.talkbank.org/ns/talkbank}nonemptyStringType" />
 *       &lt;attribute name="Media" type="{http://www.talkbank.org/ns/talkbank}mediaRefType" />
 *       &lt;attribute name="Mediatypes" type="{http://www.talkbank.org/ns/talkbank}mediaTypesType" />
 *       &lt;attribute name="Lang" use="required" type="{http://www.talkbank.org/ns/talkbank}languagesType" />
 *       &lt;attribute name="Options" type="{http://www.talkbank.org/ns/talkbank}optionsType" />
 *       &lt;attribute name="Colorwords" type="{http://www.talkbank.org/ns/talkbank}nonemptyStringType" />
 *       &lt;attribute name="PID" type="{http://www.talkbank.org/ns/talkbank}nonemptyStringType" />
 *       &lt;attribute name="Font" type="{http://www.talkbank.org/ns/talkbank}nonemptyStringType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "metadata",
    "participants",
    "commentsAndTcusAndBeginGems"
})
@XmlRootElement(name = "CHAT")
public class CHAT {

    @XmlElement(name = "Metadata")
    protected Metadata metadata;
    @XmlElement(name = "Participants", required = true)
    protected CHAT.Participants participants;
    @XmlElements({
        @XmlElement(name = "comment", type = Comment.class),
        @XmlElement(name = "tcu", type = Tcu.class),
        @XmlElement(name = "begin-gem", type = CHAT.BeginGem.class),
        @XmlElement(name = "end-gem", type = CHAT.EndGem.class),
        @XmlElement(name = "lazy-gem", type = CHAT.LazyGem.class),
        @XmlElement(name = "u", type = U.class)
    })
    protected List<Object> commentsAndTcusAndBeginGems;
    @XmlAttribute(name = "Id", required = true)
    protected String id;
    @XmlAttribute(name = "Version", required = true)
    protected String version;
    @XmlAttribute(name = "Date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar date;
    @XmlAttribute(name = "Corpus", required = true)
    protected String corpus;
    @XmlAttribute(name = "Media")
    protected String media;
    @XmlAttribute(name = "Mediatypes")
    protected List<MediaTypeType> mediatypes;
    @XmlAttribute(name = "Lang", required = true)
    protected List<String> langs;
    @XmlAttribute(name = "Options")
    protected List<OptionType> options;
    @XmlAttribute(name = "Colorwords")
    protected String colorwords;
    @XmlAttribute(name = "PID")
    protected String pid;
    @XmlAttribute(name = "Font")
    protected String font;

    /**
     * Gets the value of the metadata property.
     * 
     * @return
     *     possible object is
     *     {@link Metadata }
     *     
     */
    public Metadata getMetadata() {
        return metadata;
    }

    /**
     * Sets the value of the metadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link Metadata }
     *     
     */
    public void setMetadata(Metadata value) {
        this.metadata = value;
    }

    /**
     * Gets the value of the participants property.
     * 
     * @return
     *     possible object is
     *     {@link CHAT.Participants }
     *     
     */
    public CHAT.Participants getParticipants() {
        return participants;
    }

    /**
     * Sets the value of the participants property.
     * 
     * @param value
     *     allowed object is
     *     {@link CHAT.Participants }
     *     
     */
    public void setParticipants(CHAT.Participants value) {
        this.participants = value;
    }

    /**
     * Gets the value of the commentsAndTcusAndBeginGems property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the commentsAndTcusAndBeginGems property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCommentsAndTcusAndBeginGems().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Comment }
     * {@link Tcu }
     * {@link CHAT.BeginGem }
     * {@link CHAT.EndGem }
     * {@link CHAT.LazyGem }
     * {@link U }
     * 
     * 
     */
    public List<Object> getCommentsAndTcusAndBeginGems() {
        if (commentsAndTcusAndBeginGems == null) {
            commentsAndTcusAndBeginGems = new ArrayList<Object>();
        }
        return this.commentsAndTcusAndBeginGems;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the corpus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorpus() {
        return corpus;
    }

    /**
     * Sets the value of the corpus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorpus(String value) {
        this.corpus = value;
    }

    /**
     * Gets the value of the media property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedia() {
        return media;
    }

    /**
     * Sets the value of the media property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedia(String value) {
        this.media = value;
    }

    /**
     * Gets the value of the mediatypes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mediatypes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMediatypes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MediaTypeType }
     * 
     * 
     */
    public List<MediaTypeType> getMediatypes() {
        if (mediatypes == null) {
            mediatypes = new ArrayList<MediaTypeType>();
        }
        return this.mediatypes;
    }

    /**
     * Gets the value of the langs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the langs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLangs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getLangs() {
        if (langs == null) {
            langs = new ArrayList<String>();
        }
        return this.langs;
    }

    /**
     * Gets the value of the options property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the options property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOptions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OptionType }
     * 
     * 
     */
    public List<OptionType> getOptions() {
        if (options == null) {
            options = new ArrayList<OptionType>();
        }
        return this.options;
    }

    /**
     * Gets the value of the colorwords property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColorwords() {
        return colorwords;
    }

    /**
     * Sets the value of the colorwords property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColorwords(String value) {
        this.colorwords = value;
    }

    /**
     * Gets the value of the pid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPID() {
        return pid;
    }

    /**
     * Sets the value of the pid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPID(String value) {
        this.pid = value;
    }

    /**
     * Gets the value of the font property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFont() {
        return font;
    }

    /**
     * Sets the value of the font property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFont(String value) {
        this.font = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="label" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class BeginGem {

        @XmlAttribute(name = "label", required = true)
        protected String label;

        /**
         * Gets the value of the label property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLabel() {
            return label;
        }

        /**
         * Sets the value of the label property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLabel(String value) {
            this.label = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="label" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class EndGem {

        @XmlAttribute(name = "label", required = true)
        protected String label;

        /**
         * Gets the value of the label property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLabel() {
            return label;
        }

        /**
         * Sets the value of the label property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLabel(String value) {
            this.label = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="label" use="required" type="{http://www.talkbank.org/ns/talkbank}nonemptyStringType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class LazyGem {

        @XmlAttribute(name = "label", required = true)
        protected String label;

        /**
         * Gets the value of the label property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLabel() {
            return label;
        }

        /**
         * Sets the value of the label property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLabel(String value) {
            this.label = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="participant" type="{http://www.talkbank.org/ns/talkbank}participantType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "participants"
    })
    public static class Participants {

        @XmlElement(name = "participant", required = true)
        protected List<ParticipantType> participants;

        /**
         * Gets the value of the participants property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the participants property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getParticipants().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ParticipantType }
         * 
         * 
         */
        public List<ParticipantType> getParticipants() {
            if (participants == null) {
                participants = new ArrayList<ParticipantType>();
            }
            return this.participants;
        }

    }

}
