//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.30 at 05:39:42 PM NZDT 
//


package talkbank.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for alignmentColumn complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="alignmentColumn">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}modelref"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}actualref" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;sequence>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}actualref"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}modelref" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "alignmentColumn", propOrder = {
    "modelrevesAndActualreves"
})
@XmlRootElement(name = "col")
public class Col {

    @XmlElementRefs({
        @XmlElementRef(name = "modelref", namespace = "http://www.talkbank.org/ns/talkbank", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "actualref", namespace = "http://www.talkbank.org/ns/talkbank", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<String>> modelrevesAndActualreves;

    /**
     * Gets the value of the modelrevesAndActualreves property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the modelrevesAndActualreves property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModelrevesAndActualreves().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<String>> getModelrevesAndActualreves() {
        if (modelrevesAndActualreves == null) {
            modelrevesAndActualreves = new ArrayList<JAXBElement<String>>();
        }
        return this.modelrevesAndActualreves;
    }

}
