//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.30 at 05:39:42 PM NZDT 
//


package talkbank.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for commentTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="commentTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Activities"/>
 *     &lt;enumeration value="Bck"/>
 *     &lt;enumeration value="Date"/>
 *     &lt;enumeration value="Exceptions"/>
 *     &lt;enumeration value="Interaction Type"/>
 *     &lt;enumeration value="Number"/>
 *     &lt;enumeration value="Recording Quality"/>
 *     &lt;enumeration value="Transcription"/>
 *     &lt;enumeration value="Blank"/>
 *     &lt;enumeration value="T"/>
 *     &lt;enumeration value="Generic"/>
 *     &lt;enumeration value="New Language"/>
 *     &lt;enumeration value="Location"/>
 *     &lt;enumeration value="New Episode"/>
 *     &lt;enumeration value="Room Layout"/>
 *     &lt;enumeration value="Situation"/>
 *     &lt;enumeration value="Tape Location"/>
 *     &lt;enumeration value="Time Duration"/>
 *     &lt;enumeration value="Time Start"/>
 *     &lt;enumeration value="Transcriber"/>
 *     &lt;enumeration value="Warning"/>
 *     &lt;enumeration value="Page"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "commentTypeType")
@XmlEnum
public enum CommentTypeType {


    /**
     * 
     *                         
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;a xmlns="http://www.w3.org/1999/xhtml" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:tb="http://www.talkbank.org/ns/talkbank" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:xs="http://www.w3.org/2001/XMLSchema" href="http://childes.psy.cmu.edu/manuals/chat.html#Activities_Header"&gt;
     *                             CHAT manual
     *                             section on this topic...
     *                         &lt;/a&gt;
     * </pre>
     * 
     *                     
     * 
     */
    @XmlEnumValue("Activities")
    ACTIVITIES("Activities"),

    /**
     * 
     *                         
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;a xmlns="http://www.w3.org/1999/xhtml" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:tb="http://www.talkbank.org/ns/talkbank" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:xs="http://www.w3.org/2001/XMLSchema" href="http://childes.psy.cmu.edu/manuals/chat.html#Bck_Header"&gt;
     *                             CHAT manual section on
     *                             this topic...
     *                         &lt;/a&gt;
     * </pre>
     * 
     *                     
     * 
     */
    @XmlEnumValue("Bck")
    BCK("Bck"),

    /**
     * 
     *                         
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;a xmlns="http://www.w3.org/1999/xhtml" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:tb="http://www.talkbank.org/ns/talkbank" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:xs="http://www.w3.org/2001/XMLSchema" href="http://childes.psy.cmu.edu/manuals/chat.html#Date_Header"&gt;
     *                             CHAT manual section
     *                             on this topic...
     *                         &lt;/a&gt;
     * </pre>
     * 
     *                     
     * 
     */
    @XmlEnumValue("Date")
    DATE("Date"),

    /**
     * 
     *                         
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;a xmlns="http://www.w3.org/1999/xhtml" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:tb="http://www.talkbank.org/ns/talkbank" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:xs="http://www.w3.org/2001/XMLSchema" href="http://childes.psy.cmu.edu/manuals/chat.html#Exceptions_Header"&gt;
     *                             CHAT manual
     *                             section on this topic...
     *                         &lt;/a&gt;
     * </pre>
     * 
     *                     
     * 
     */
    @XmlEnumValue("Exceptions")
    EXCEPTIONS("Exceptions"),

    /**
     * 
     *                         
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;a xmlns="http://www.w3.org/1999/xhtml" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:tb="http://www.talkbank.org/ns/talkbank" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:xs="http://www.w3.org/2001/XMLSchema" href="http://childes.psy.cmu.edu/manuals/chat.html#Interaction_Type_Header"&gt;
     *                             CHAT
     *                             manual section on this topic...
     *                         &lt;/a&gt;
     * </pre>
     * 
     *                     
     * 
     */
    @XmlEnumValue("Interaction Type")
    INTERACTION_TYPE("Interaction Type"),

    /**
     * 
     *                         
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;a xmlns="http://www.w3.org/1999/xhtml" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:tb="http://www.talkbank.org/ns/talkbank" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:xs="http://www.w3.org/2001/XMLSchema" href="http://childes.psy.cmu.edu/manuals/chat.html#Number_Header"&gt;
     *                             CHAT manual section
     *                             on this topic...
     *                         &lt;/a&gt;
     * </pre>
     * 
     *                     
     * 
     */
    @XmlEnumValue("Number")
    NUMBER("Number"),

    /**
     * 
     *                         
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;a xmlns="http://www.w3.org/1999/xhtml" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:tb="http://www.talkbank.org/ns/talkbank" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:xs="http://www.w3.org/2001/XMLSchema" href="http://childes.psy.cmu.edu/manuals/chat.html#Recording_Quality_Header"&gt;
     *                             CHAT
     *                             manual section on this topic...
     *                         &lt;/a&gt;
     * </pre>
     * 
     *                     
     * 
     */
    @XmlEnumValue("Recording Quality")
    RECORDING_QUALITY("Recording Quality"),

    /**
     * 
     *                         
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;a xmlns="http://www.w3.org/1999/xhtml" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:tb="http://www.talkbank.org/ns/talkbank" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:xs="http://www.w3.org/2001/XMLSchema" href="http://childes.psy.cmu.edu/manuals/chat.html#Transcription_Header"&gt;
     *                             CHAT manual
     *                             section on this topic...
     *                         &lt;/a&gt;
     * </pre>
     * 
     *                     
     * 
     */
    @XmlEnumValue("Transcription")
    TRANSCRIPTION("Transcription"),

    /**
     * 
     *                         
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;a xmlns="http://www.w3.org/1999/xhtml" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:tb="http://www.talkbank.org/ns/talkbank" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:xs="http://www.w3.org/2001/XMLSchema" href="http://childes.psy.cmu.edu/manuals/chat.html#Blank_Header"&gt;
     *                             CHAT manual section
     *                             on this topic...
     *                         &lt;/a&gt;
     * </pre>
     * 
     *                     
     * 
     */
    @XmlEnumValue("Blank")
    BLANK("Blank"),

    /**
     * 
     *                         
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;a xmlns="http://www.w3.org/1999/xhtml" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:tb="http://www.talkbank.org/ns/talkbank" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:xs="http://www.w3.org/2001/XMLSchema" href="http://childes.psy.cmu.edu/manuals/chat.html#Thumbnail_Header"&gt;
     *                             CHAT manual
     *                             section on this topic...
     *                         &lt;/a&gt;
     * </pre>
     * 
     *                     
     * 
     */
    T("T"),

    /**
     * 
     *                         
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;a xmlns="http://www.w3.org/1999/xhtml" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:tb="http://www.talkbank.org/ns/talkbank" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:xs="http://www.w3.org/2001/XMLSchema" href="http://childes.psy.cmu.edu/manuals/chat.html#Comment_Header"&gt;
     *                             CHAT manual
     *                             section on this topic...
     *                         &lt;/a&gt;
     * </pre>
     * 
     *                     
     * 
     */
    @XmlEnumValue("Generic")
    GENERIC("Generic"),

    /**
     * 
     *                         
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;a xmlns="http://www.w3.org/1999/xhtml" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:tb="http://www.talkbank.org/ns/talkbank" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:xs="http://www.w3.org/2001/XMLSchema" href="http://childes.psy.cmu.edu/manuals/chat.html#New_Language_Header"&gt;
     *                             CHAT manual
     *                             section on this topic...
     *                         &lt;/a&gt;
     * </pre>
     * 
     *                     
     * 
     */
    @XmlEnumValue("New Language")
    NEW_LANGUAGE("New Language"),

    /**
     * 
     *                         
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;a xmlns="http://www.w3.org/1999/xhtml" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:tb="http://www.talkbank.org/ns/talkbank" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:xs="http://www.w3.org/2001/XMLSchema" href="http://childes.psy.cmu.edu/manuals/chat.html#Location_Header"&gt;
     *                             CHAT manual
     *                             section on this topic...
     *                         &lt;/a&gt;
     * </pre>
     * 
     *                     
     * 
     */
    @XmlEnumValue("Location")
    LOCATION("Location"),

    /**
     * 
     *                         
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;a xmlns="http://www.w3.org/1999/xhtml" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:tb="http://www.talkbank.org/ns/talkbank" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:xs="http://www.w3.org/2001/XMLSchema" href="http://childes.psy.cmu.edu/manuals/chat.html#New_Episode_Header"&gt;
     *                             CHAT manual
     *                             section on this topic...
     *                         &lt;/a&gt;
     * </pre>
     * 
     *                     
     * 
     */
    @XmlEnumValue("New Episode")
    NEW_EPISODE("New Episode"),

    /**
     * 
     *                         
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;a xmlns="http://www.w3.org/1999/xhtml" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:tb="http://www.talkbank.org/ns/talkbank" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:xs="http://www.w3.org/2001/XMLSchema" href="http://childes.psy.cmu.edu/manuals/chat.html#Room_Layout_Header"&gt;
     *                             CHAT manual
     *                             section on this topic...
     *                         &lt;/a&gt;
     * </pre>
     * 
     *                     
     * 
     */
    @XmlEnumValue("Room Layout")
    ROOM_LAYOUT("Room Layout"),

    /**
     * 
     *                         
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;a xmlns="http://www.w3.org/1999/xhtml" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:tb="http://www.talkbank.org/ns/talkbank" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:xs="http://www.w3.org/2001/XMLSchema" href="http://childes.psy.cmu.edu/manuals/chat.html#Situation_Header"&gt;
     *                             CHAT manual
     *                             section on this topic...
     *                         &lt;/a&gt;
     * </pre>
     * 
     *                     
     * 
     */
    @XmlEnumValue("Situation")
    SITUATION("Situation"),

    /**
     * 
     *                         
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;a xmlns="http://www.w3.org/1999/xhtml" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:tb="http://www.talkbank.org/ns/talkbank" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:xs="http://www.w3.org/2001/XMLSchema" href="http://childes.psy.cmu.edu/manuals/chat.html#Tape_Location_Header"&gt;
     *                             CHAT manual
     *                             section on this topic...
     *                         &lt;/a&gt;
     * </pre>
     * 
     *                     
     * 
     */
    @XmlEnumValue("Tape Location")
    TAPE_LOCATION("Tape Location"),

    /**
     * 
     *                         
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;a xmlns="http://www.w3.org/1999/xhtml" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:tb="http://www.talkbank.org/ns/talkbank" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:xs="http://www.w3.org/2001/XMLSchema" href="http://childes.psy.cmu.edu/manuals/chat.html#Time_Duration_Header"&gt;
     *                             CHAT manual
     *                             section on this topic...
     *                         &lt;/a&gt;
     * </pre>
     * 
     *                     
     * 
     */
    @XmlEnumValue("Time Duration")
    TIME_DURATION("Time Duration"),

    /**
     * 
     *                         
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;a xmlns="http://www.w3.org/1999/xhtml" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:tb="http://www.talkbank.org/ns/talkbank" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:xs="http://www.w3.org/2001/XMLSchema" href="http://childes.psy.cmu.edu/manuals/chat.html#Time_Start_Header"&gt;
     *                             CHAT manual
     *                             section on this topic...
     *                         &lt;/a&gt;
     * </pre>
     * 
     *                     
     * 
     */
    @XmlEnumValue("Time Start")
    TIME_START("Time Start"),

    /**
     * 
     *                         
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;a xmlns="http://www.w3.org/1999/xhtml" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:tb="http://www.talkbank.org/ns/talkbank" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:xs="http://www.w3.org/2001/XMLSchema" href="http://childes.psy.cmu.edu/manuals/chat.html#Transcriber_Header"&gt;
     *                             CHAT manual
     *                             section on this topic...
     *                         &lt;/a&gt;
     * </pre>
     * 
     *                     
     * 
     */
    @XmlEnumValue("Transcriber")
    TRANSCRIBER("Transcriber"),

    /**
     * 
     *                         
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;a xmlns="http://www.w3.org/1999/xhtml" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:tb="http://www.talkbank.org/ns/talkbank" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:xs="http://www.w3.org/2001/XMLSchema" href="http://childes.psy.cmu.edu/manuals/chat.html#Warning_Header"&gt;
     *                             CHAT manual
     *                             section on this topic...
     *                         &lt;/a&gt;
     * </pre>
     * 
     *                     
     * 
     */
    @XmlEnumValue("Warning")
    WARNING("Warning"),

    /**
     * 
     *                         
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;a xmlns="http://www.w3.org/1999/xhtml" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:tb="http://www.talkbank.org/ns/talkbank" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:xs="http://www.w3.org/2001/XMLSchema" href="http://childes.psy.cmu.edu/manuals/chat.html#Page_Header"&gt;
     *                             CHAT manual section
     *                             on this topic...
     *                         &lt;/a&gt;
     * </pre>
     * 
     *                     
     * 
     */
    @XmlEnumValue("Page")
    PAGE("Page");
    private final String value;

    CommentTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CommentTypeType fromValue(String v) {
        for (CommentTypeType c: CommentTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
