//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.30 at 05:39:42 PM NZDT 
//


package talkbank.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for constituentTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="constituentTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="SB"/>
 *     &lt;enumeration value="SS"/>
 *     &lt;enumeration value="LA"/>
 *     &lt;enumeration value="O"/>
 *     &lt;enumeration value="N"/>
 *     &lt;enumeration value="C"/>
 *     &lt;enumeration value="RA"/>
 *     &lt;enumeration value="OEHS"/>
 *     &lt;enumeration value="AS"/>
 *     &lt;enumeration value="UK"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "constituentTypeType")
@XmlEnum
public enum ConstituentTypeType {


    /**
     * Syllable boundary marker ('.')
     * 
     */
    SB,

    /**
     * 
     *                         Deprecated: use stress attribute of syll_start
     *                         instead
     *                     
     * 
     */
    SS,

    /**
     * Left appendix
     * 
     */
    LA,

    /**
     * Onset
     * 
     */
    O,

    /**
     * Nucleus
     * 
     */
    N,

    /**
     * Coda
     * 
     */
    C,

    /**
     * Right appendix
     * 
     */
    RA,

    /**
     * Onset of an empty headed syllable
     * 
     */
    OEHS,

    /**
     * Ambisyllabic
     * 
     */
    AS,

    /**
     * Unknown
     * 
     */
    UK;

    public String value() {
        return name();
    }

    public static ConstituentTypeType fromValue(String v) {
        return valueOf(v);
    }

}
