//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.30 at 05:39:42 PM NZDT 
//


package talkbank.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mediaUnitType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="mediaUnitType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="f"/>
 *     &lt;enumeration value="s"/>
 *     &lt;enumeration value="ms"/>
 *     &lt;enumeration value="b"/>
 *     &lt;enumeration value="c"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "mediaUnitType")
@XmlEnum
public enum MediaUnitType {


    /**
     * frame
     * 
     */
    @XmlEnumValue("f")
    F("f"),

    /**
     * second
     * 
     */
    @XmlEnumValue("s")
    S("s"),

    /**
     * millisecond
     * 
     */
    @XmlEnumValue("ms")
    MS("ms"),

    /**
     * byte
     * 
     */
    @XmlEnumValue("b")
    B("b"),

    /**
     * character
     * 
     */
    @XmlEnumValue("c")
    C("c");
    private final String value;

    MediaUnitType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MediaUnitType fromValue(String v) {
        for (MediaUnitType c: MediaUnitType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
