//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.30 at 05:39:42 PM NZDT 
//


package talkbank.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 administrative descriptions, reused from Dublin Core
 *             
 * 
 * <p>Java class for Metadata complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Metadata">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{http://www.talkbank.org/ns/talkbank}DCelementsGroup"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Metadata", propOrder = {
    "titlesAndCreatorsAndSubjects"
})
public class Metadata {

    @XmlElementRefs({
        @XmlElementRef(name = "subject", namespace = "http://www.talkbank.org/ns/talkbank", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "date", namespace = "http://www.talkbank.org/ns/talkbank", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "language", namespace = "http://www.talkbank.org/ns/talkbank", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "contributor", namespace = "http://www.talkbank.org/ns/talkbank", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "title", namespace = "http://www.talkbank.org/ns/talkbank", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "creator", namespace = "http://www.talkbank.org/ns/talkbank", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "identifier", namespace = "http://www.talkbank.org/ns/talkbank", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "format", namespace = "http://www.talkbank.org/ns/talkbank", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "coverage", namespace = "http://www.talkbank.org/ns/talkbank", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "appId", namespace = "http://www.talkbank.org/ns/talkbank", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "description", namespace = "http://www.talkbank.org/ns/talkbank", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "relation", namespace = "http://www.talkbank.org/ns/talkbank", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "rights", namespace = "http://www.talkbank.org/ns/talkbank", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "source", namespace = "http://www.talkbank.org/ns/talkbank", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "type", namespace = "http://www.talkbank.org/ns/talkbank", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "publisher", namespace = "http://www.talkbank.org/ns/talkbank", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<DCelementType>> titlesAndCreatorsAndSubjects;

    /**
     * Gets the value of the titlesAndCreatorsAndSubjects property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the titlesAndCreatorsAndSubjects property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTitlesAndCreatorsAndSubjects().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link DCelementType }{@code >}
     * {@link JAXBElement }{@code <}{@link DCelementType }{@code >}
     * {@link JAXBElement }{@code <}{@link DCelementType }{@code >}
     * {@link JAXBElement }{@code <}{@link DCelementType }{@code >}
     * {@link JAXBElement }{@code <}{@link DCelementType }{@code >}
     * {@link JAXBElement }{@code <}{@link DCelementType }{@code >}
     * {@link JAXBElement }{@code <}{@link DCelementType }{@code >}
     * {@link JAXBElement }{@code <}{@link DCelementType }{@code >}
     * {@link JAXBElement }{@code <}{@link DCelementType }{@code >}
     * {@link JAXBElement }{@code <}{@link DCelementType }{@code >}
     * {@link JAXBElement }{@code <}{@link DCelementType }{@code >}
     * {@link JAXBElement }{@code <}{@link DCelementType }{@code >}
     * {@link JAXBElement }{@code <}{@link DCelementType }{@code >}
     * {@link JAXBElement }{@code <}{@link DCelementType }{@code >}
     * {@link JAXBElement }{@code <}{@link DCelementType }{@code >}
     * {@link JAXBElement }{@code <}{@link DCelementType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<DCelementType>> getTitlesAndCreatorsAndSubjects() {
        if (titlesAndCreatorsAndSubjects == null) {
            titlesAndCreatorsAndSubjects = new ArrayList<JAXBElement<DCelementType>>();
        }
        return this.titlesAndCreatorsAndSubjects;
    }

}
