//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.30 at 05:39:42 PM NZDT 
//


package talkbank.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;a xmlns="http://www.w3.org/1999/xhtml" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:tb="http://www.talkbank.org/ns/talkbank" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:xs="http://www.w3.org/2001/XMLSchema" href="http://childes.psy.cmu.edu/manuals/chat.html#Morphological_Tier"&gt;
 *                     CHAT manual
 *                     section on this topic...
 *                 &lt;/a&gt;
 * </pre>
 * 
 *             
 * 
 * <p>Java class for morType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="morType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.talkbank.org/ns/talkbank}morphemicBaseType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.talkbank.org/ns/talkbank}mor-pre" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.talkbank.org/ns/talkbank}mor-post" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" use="required" type="{http://www.talkbank.org/ns/talkbank}nonemptyStringType" />
 *       &lt;attribute name="omitted" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "morType", propOrder = {
    "morPres",
    "morPosts"
})
@XmlRootElement(name = "mor")
public class Mor
    extends MorphemicBaseType
{

    @XmlElement(name = "mor-pre")
    protected List<MorphemicBaseType> morPres;
    @XmlElement(name = "mor-post")
    protected List<MorphemicBaseType> morPosts;
    @XmlAttribute(name = "type", required = true)
    protected String type;
    @XmlAttribute(name = "omitted")
    protected Boolean omitted;

    /**
     * Gets the value of the morPres property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the morPres property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMorPres().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MorphemicBaseType }
     * 
     * 
     */
    public List<MorphemicBaseType> getMorPres() {
        if (morPres == null) {
            morPres = new ArrayList<MorphemicBaseType>();
        }
        return this.morPres;
    }

    /**
     * Gets the value of the morPosts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the morPosts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMorPosts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MorphemicBaseType }
     * 
     * 
     */
    public List<MorphemicBaseType> getMorPosts() {
        if (morPosts == null) {
            morPosts = new ArrayList<MorphemicBaseType>();
        }
        return this.morPosts;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the omitted property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOmitted() {
        return omitted;
    }

    /**
     * Sets the value of the omitted property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOmitted(Boolean value) {
        this.omitted = value;
    }

}
