//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.30 at 05:39:42 PM NZDT 
//


package talkbank.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;a xmlns="http://www.w3.org/1999/xhtml" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:tb="http://www.talkbank.org/ns/talkbank" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:xs="http://www.w3.org/2001/XMLSchema" href="http://childes.psy.cmu.edu/manuals/chat.html#Morphological_Word"&gt;
 *                     CHAT manual
 *                     section on this topic...
 *                 &lt;/a&gt;
 * </pre>
 * 
 *             
 * 
 * <p>Java class for morphemicBaseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="morphemicBaseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}mw"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}mwc"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}mt"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.talkbank.org/ns/talkbank}menx" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.talkbank.org/ns/talkbank}gra" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "morphemicBaseType", propOrder = {
    "mt",
    "mwc",
    "mw",
    "menxes",
    "gras"
})
@XmlSeeAlso({
    Mor.class
})
public class MorphemicBaseType {

    protected BaseTerminatorType mt;
    protected Mwc mwc;
    protected Mw mw;
    @XmlElement(name = "menx")
    protected List<Menx> menxes;
    @XmlElement(name = "gra")
    protected List<Gra> gras;

    /**
     * Gets the value of the mt property.
     * 
     * @return
     *     possible object is
     *     {@link BaseTerminatorType }
     *     
     */
    public BaseTerminatorType getMt() {
        return mt;
    }

    /**
     * Sets the value of the mt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BaseTerminatorType }
     *     
     */
    public void setMt(BaseTerminatorType value) {
        this.mt = value;
    }

    /**
     * Gets the value of the mwc property.
     * 
     * @return
     *     possible object is
     *     {@link Mwc }
     *     
     */
    public Mwc getMwc() {
        return mwc;
    }

    /**
     * Sets the value of the mwc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mwc }
     *     
     */
    public void setMwc(Mwc value) {
        this.mwc = value;
    }

    /**
     * Gets the value of the mw property.
     * 
     * @return
     *     possible object is
     *     {@link Mw }
     *     
     */
    public Mw getMw() {
        return mw;
    }

    /**
     * Sets the value of the mw property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mw }
     *     
     */
    public void setMw(Mw value) {
        this.mw = value;
    }

    /**
     * Gets the value of the menxes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the menxes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMenxes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Menx }
     * 
     * 
     */
    public List<Menx> getMenxes() {
        if (menxes == null) {
            menxes = new ArrayList<Menx>();
        }
        return this.menxes;
    }

    /**
     * Gets the value of the gras property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the gras property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGras().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Gra }
     * 
     * 
     */
    public List<Gra> getGras() {
        if (gras == null) {
            gras = new ArrayList<Gra>();
        }
        return this.gras;
    }

}
