//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.30 at 05:39:42 PM NZDT 
//


package talkbank.schema;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.talkbank.ns.talkbank package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Actualref_QNAME = new QName("http://www.talkbank.org/ns/talkbank", "actualref");
    private final static QName _C_QNAME = new QName("http://www.talkbank.org/ns/talkbank", "c");
    private final static QName _Mt_QNAME = new QName("http://www.talkbank.org/ns/talkbank", "mt");
    private final static QName _MorPre_QNAME = new QName("http://www.talkbank.org/ns/talkbank", "mor-pre");
    private final static QName _Media_QNAME = new QName("http://www.talkbank.org/ns/talkbank", "media");
    private final static QName _Error_QNAME = new QName("http://www.talkbank.org/ns/talkbank", "error");
    private final static QName _Modelref_QNAME = new QName("http://www.talkbank.org/ns/talkbank", "modelref");
    private final static QName _Duration_QNAME = new QName("http://www.talkbank.org/ns/talkbank", "duration");
    private final static QName _InternalMedia_QNAME = new QName("http://www.talkbank.org/ns/talkbank", "internal-media");
    private final static QName _MorPost_QNAME = new QName("http://www.talkbank.org/ns/talkbank", "mor-post");
    private final static QName _Action_QNAME = new QName("http://www.talkbank.org/ns/talkbank", "action");
    private final static QName _Happening_QNAME = new QName("http://www.talkbank.org/ns/talkbank", "happening");
    private final static QName _Stem_QNAME = new QName("http://www.talkbank.org/ns/talkbank", "stem");
    private final static QName _MetadataDate_QNAME = new QName("http://www.talkbank.org/ns/talkbank", "date");
    private final static QName _MetadataCoverage_QNAME = new QName("http://www.talkbank.org/ns/talkbank", "coverage");
    private final static QName _MetadataIdentifier_QNAME = new QName("http://www.talkbank.org/ns/talkbank", "identifier");
    private final static QName _MetadataCreator_QNAME = new QName("http://www.talkbank.org/ns/talkbank", "creator");
    private final static QName _MetadataSubject_QNAME = new QName("http://www.talkbank.org/ns/talkbank", "subject");
    private final static QName _MetadataFormat_QNAME = new QName("http://www.talkbank.org/ns/talkbank", "format");
    private final static QName _MetadataDescription_QNAME = new QName("http://www.talkbank.org/ns/talkbank", "description");
    private final static QName _MetadataLanguage_QNAME = new QName("http://www.talkbank.org/ns/talkbank", "language");
    private final static QName _MetadataSource_QNAME = new QName("http://www.talkbank.org/ns/talkbank", "source");
    private final static QName _MetadataTitle_QNAME = new QName("http://www.talkbank.org/ns/talkbank", "title");
    private final static QName _MetadataType_QNAME = new QName("http://www.talkbank.org/ns/talkbank", "type");
    private final static QName _MetadataRelation_QNAME = new QName("http://www.talkbank.org/ns/talkbank", "relation");
    private final static QName _MetadataContributor_QNAME = new QName("http://www.talkbank.org/ns/talkbank", "contributor");
    private final static QName _MetadataRights_QNAME = new QName("http://www.talkbank.org/ns/talkbank", "rights");
    private final static QName _MetadataAppId_QNAME = new QName("http://www.talkbank.org/ns/talkbank", "appId");
    private final static QName _MetadataPublisher_QNAME = new QName("http://www.talkbank.org/ns/talkbank", "publisher");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.talkbank.ns.talkbank
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CHAT }
     * 
     */
    public CHAT createCHAT() {
        return new CHAT();
    }

    /**
     * Create an instance of {@link AGSet }
     * 
     */
    public AGSet createAGSet() {
        return new AGSet();
    }

    /**
     * Create an instance of {@link AGSet.AG }
     * 
     */
    public AGSet.AG createAGSetAG() {
        return new AGSet.AG();
    }

    /**
     * Create an instance of {@link AGSet.AG.Annotation }
     * 
     */
    public AGSet.AG.Annotation createAGSetAGAnnotation() {
        return new AGSet.AG.Annotation();
    }

    /**
     * Create an instance of {@link AGSet.Timeline }
     * 
     */
    public AGSet.Timeline createAGSetTimeline() {
        return new AGSet.Timeline();
    }

    /**
     * Create an instance of {@link Col }
     * 
     */
    public Col createCol() {
        return new Col();
    }

    /**
     * Create an instance of {@link Underline }
     * 
     */
    public Underline createUnderline() {
        return new Underline();
    }

    /**
     * Create an instance of {@link Mpfx }
     * 
     */
    public Mpfx createMpfx() {
        return new Mpfx();
    }

    /**
     * Create an instance of {@link Pw }
     * 
     */
    public Pw createPw() {
        return new Pw();
    }

    /**
     * Create an instance of {@link Ss }
     * 
     */
    public Ss createSs() {
        return new Ss();
    }

    /**
     * Create an instance of {@link Wk }
     * 
     */
    public Wk createWk() {
        return new Wk();
    }

    /**
     * Create an instance of {@link Ph }
     * 
     */
    public Ph createPh() {
        return new Ph();
    }

    /**
     * Create an instance of {@link Freecode }
     * 
     */
    public Freecode createFreecode() {
        return new Freecode();
    }

    /**
     * Create an instance of {@link Align }
     * 
     */
    public Align createAlign() {
        return new Align();
    }

    /**
     * Create an instance of {@link CaDelimiter }
     * 
     */
    public CaDelimiter createCaDelimiter() {
        return new CaDelimiter();
    }

    /**
     * Create an instance of {@link Italic }
     * 
     */
    public Italic createItalic() {
        return new Italic();
    }

    /**
     * Create an instance of {@link Mor }
     * 
     */
    public Mor createMor() {
        return new Mor();
    }

    /**
     * Create an instance of {@link MorphemicBaseType }
     * 
     */
    public MorphemicBaseType createMorphemicBaseType() {
        return new MorphemicBaseType();
    }

    /**
     * Create an instance of {@link BaseTerminatorType }
     * 
     */
    public BaseTerminatorType createBaseTerminatorType() {
        return new BaseTerminatorType();
    }

    /**
     * Create an instance of {@link Mwc }
     * 
     */
    public Mwc createMwc() {
        return new Mwc();
    }

    /**
     * Create an instance of {@link Pos }
     * 
     */
    public Pos createPos() {
        return new Pos();
    }

    /**
     * Create an instance of {@link Mw }
     * 
     */
    public Mw createMw() {
        return new Mw();
    }

    /**
     * Create an instance of {@link Mk }
     * 
     */
    public Mk createMk() {
        return new Mk();
    }

    /**
     * Create an instance of {@link Menx }
     * 
     */
    public Menx createMenx() {
        return new Menx();
    }

    /**
     * Create an instance of {@link Gra }
     * 
     */
    public Gra createGra() {
        return new Gra();
    }

    /**
     * Create an instance of {@link TagMarker }
     * 
     */
    public TagMarker createTagMarker() {
        return new TagMarker();
    }

    /**
     * Create an instance of {@link OtherSpokenEvent }
     * 
     */
    public OtherSpokenEvent createOtherSpokenEvent() {
        return new OtherSpokenEvent();
    }

    /**
     * Create an instance of {@link W }
     * 
     */
    public W createW() {
        return new W();
    }

    /**
     * Create an instance of {@link Langs }
     * 
     */
    public Langs createLangs() {
        return new Langs();
    }

    /**
     * Create an instance of {@link OverlapPoint }
     * 
     */
    public OverlapPoint createOverlapPoint() {
        return new OverlapPoint();
    }

    /**
     * Create an instance of {@link Shortening }
     * 
     */
    public Shortening createShortening() {
        return new Shortening();
    }

    /**
     * Create an instance of {@link P }
     * 
     */
    public P createP() {
        return new P();
    }

    /**
     * Create an instance of {@link LongFeature }
     * 
     */
    public LongFeature createLongFeature() {
        return new LongFeature();
    }

    /**
     * Create an instance of {@link CaElement }
     * 
     */
    public CaElement createCaElement() {
        return new CaElement();
    }

    /**
     * Create an instance of {@link Replacement }
     * 
     */
    public Replacement createReplacement() {
        return new Replacement();
    }

    /**
     * Create an instance of {@link Model }
     * 
     */
    public Model createModel() {
        return new Model();
    }

    /**
     * Create an instance of {@link PhoType }
     * 
     */
    public PhoType createPhoType() {
        return new PhoType();
    }

    /**
     * Create an instance of {@link Actual }
     * 
     */
    public Actual createActual() {
        return new Actual();
    }

    /**
     * Create an instance of {@link Postcode }
     * 
     */
    public Postcode createPostcode() {
        return new Postcode();
    }

    /**
     * Create an instance of {@link Pause }
     * 
     */
    public Pause createPause() {
        return new Pause();
    }

    /**
     * Create an instance of {@link Overlap }
     * 
     */
    public Overlap createOverlap() {
        return new Overlap();
    }

    /**
     * Create an instance of {@link Blob }
     * 
     */
    public Blob createBlob() {
        return new Blob();
    }

    /**
     * Create an instance of {@link Nonvocal }
     * 
     */
    public Nonvocal createNonvocal() {
        return new Nonvocal();
    }

    /**
     * Create an instance of {@link Metadata }
     * 
     */
    public Metadata createMetadata() {
        return new Metadata();
    }

    /**
     * Create an instance of {@link CHAT.Participants }
     * 
     */
    public CHAT.Participants createCHATParticipants() {
        return new CHAT.Participants();
    }

    /**
     * Create an instance of {@link Comment }
     * 
     */
    public Comment createComment() {
        return new Comment();
    }

    /**
     * Create an instance of {@link MediaType }
     * 
     */
    public MediaType createMediaType() {
        return new MediaType();
    }

    /**
     * Create an instance of {@link MediaPic }
     * 
     */
    public MediaPic createMediaPic() {
        return new MediaPic();
    }

    /**
     * Create an instance of {@link Tcu }
     * 
     */
    public Tcu createTcu() {
        return new Tcu();
    }

    /**
     * Create an instance of {@link U }
     * 
     */
    public U createU() {
        return new U();
    }

    /**
     * Create an instance of {@link LinkerType }
     * 
     */
    public LinkerType createLinkerType() {
        return new LinkerType();
    }

    /**
     * Create an instance of {@link G }
     * 
     */
    public G createG() {
        return new G();
    }

    /**
     * Create an instance of {@link Pg }
     * 
     */
    public Pg createPg() {
        return new Pg();
    }

    /**
     * Create an instance of {@link Quotation }
     * 
     */
    public Quotation createQuotation() {
        return new Quotation();
    }

    /**
     * Create an instance of {@link Quotation2 }
     * 
     */
    public Quotation2 createQuotation2() {
        return new Quotation2();
    }

    /**
     * Create an instance of {@link E }
     * 
     */
    public E createE() {
        return new E();
    }

    /**
     * Create an instance of {@link K }
     * 
     */
    public K createK() {
        return new K();
    }

    /**
     * Create an instance of {@link R }
     * 
     */
    public R createR() {
        return new R();
    }

    /**
     * Create an instance of {@link Ga }
     * 
     */
    public Ga createGa() {
        return new Ga();
    }

    /**
     * Create an instance of {@link S }
     * 
     */
    public S createS() {
        return new S();
    }

    /**
     * Create an instance of {@link Sg }
     * 
     */
    public Sg createSg() {
        return new Sg();
    }

    /**
     * Create an instance of {@link Sw }
     * 
     */
    public Sw createSw() {
        return new Sw();
    }

    /**
     * Create an instance of {@link T }
     * 
     */
    public T createT() {
        return new T();
    }

    /**
     * Create an instance of {@link A }
     * 
     */
    public A createA() {
        return new A();
    }

    /**
     * Create an instance of {@link CHAT.BeginGem }
     * 
     */
    public CHAT.BeginGem createCHATBeginGem() {
        return new CHAT.BeginGem();
    }

    /**
     * Create an instance of {@link CHAT.EndGem }
     * 
     */
    public CHAT.EndGem createCHATEndGem() {
        return new CHAT.EndGem();
    }

    /**
     * Create an instance of {@link CHAT.LazyGem }
     * 
     */
    public CHAT.LazyGem createCHATLazyGem() {
        return new CHAT.LazyGem();
    }

    /**
     * Create an instance of {@link DCelementType }
     * 
     */
    public DCelementType createDCelementType() {
        return new DCelementType();
    }

    /**
     * Create an instance of {@link ParticipantType }
     * 
     */
    public ParticipantType createParticipantType() {
        return new ParticipantType();
    }

    /**
     * Create an instance of {@link AGSet.AG.Anchor }
     * 
     */
    public AGSet.AG.Anchor createAGSetAGAnchor() {
        return new AGSet.AG.Anchor();
    }

    /**
     * Create an instance of {@link AGSet.AG.Annotation.Feature }
     * 
     */
    public AGSet.AG.Annotation.Feature createAGSetAGAnnotationFeature() {
        return new AGSet.AG.Annotation.Feature();
    }

    /**
     * Create an instance of {@link AGSet.Timeline.Signal }
     * 
     */
    public AGSet.Timeline.Signal createAGSetTimelineSignal() {
        return new AGSet.Timeline.Signal();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.talkbank.org/ns/talkbank", name = "actualref")
    public JAXBElement<String> createActualref(String value) {
        return new JAXBElement<String>(_Actualref_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.talkbank.org/ns/talkbank", name = "c")
    public JAXBElement<String> createC(String value) {
        return new JAXBElement<String>(_C_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseTerminatorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.talkbank.org/ns/talkbank", name = "mt")
    public JAXBElement<BaseTerminatorType> createMt(BaseTerminatorType value) {
        return new JAXBElement<BaseTerminatorType>(_Mt_QNAME, BaseTerminatorType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MorphemicBaseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.talkbank.org/ns/talkbank", name = "mor-pre")
    public JAXBElement<MorphemicBaseType> createMorPre(MorphemicBaseType value) {
        return new JAXBElement<MorphemicBaseType>(_MorPre_QNAME, MorphemicBaseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MediaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.talkbank.org/ns/talkbank", name = "media")
    public JAXBElement<MediaType> createMedia(MediaType value) {
        return new JAXBElement<MediaType>(_Media_QNAME, MediaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.talkbank.org/ns/talkbank", name = "error")
    public JAXBElement<String> createError(String value) {
        return new JAXBElement<String>(_Error_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.talkbank.org/ns/talkbank", name = "modelref")
    public JAXBElement<String> createModelref(String value) {
        return new JAXBElement<String>(_Modelref_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.talkbank.org/ns/talkbank", name = "duration")
    public JAXBElement<BigDecimal> createDuration(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Duration_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MediaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.talkbank.org/ns/talkbank", name = "internal-media")
    public JAXBElement<MediaType> createInternalMedia(MediaType value) {
        return new JAXBElement<MediaType>(_InternalMedia_QNAME, MediaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MorphemicBaseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.talkbank.org/ns/talkbank", name = "mor-post")
    public JAXBElement<MorphemicBaseType> createMorPost(MorphemicBaseType value) {
        return new JAXBElement<MorphemicBaseType>(_MorPost_QNAME, MorphemicBaseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.talkbank.org/ns/talkbank", name = "action")
    public JAXBElement<Object> createAction(Object value) {
        return new JAXBElement<Object>(_Action_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.talkbank.org/ns/talkbank", name = "happening")
    public JAXBElement<String> createHappening(String value) {
        return new JAXBElement<String>(_Happening_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.talkbank.org/ns/talkbank", name = "stem")
    public JAXBElement<String> createStem(String value) {
        return new JAXBElement<String>(_Stem_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DCelementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.talkbank.org/ns/talkbank", name = "date", scope = Metadata.class)
    public JAXBElement<DCelementType> createMetadataDate(DCelementType value) {
        return new JAXBElement<DCelementType>(_MetadataDate_QNAME, DCelementType.class, Metadata.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DCelementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.talkbank.org/ns/talkbank", name = "coverage", scope = Metadata.class)
    public JAXBElement<DCelementType> createMetadataCoverage(DCelementType value) {
        return new JAXBElement<DCelementType>(_MetadataCoverage_QNAME, DCelementType.class, Metadata.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DCelementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.talkbank.org/ns/talkbank", name = "identifier", scope = Metadata.class)
    public JAXBElement<DCelementType> createMetadataIdentifier(DCelementType value) {
        return new JAXBElement<DCelementType>(_MetadataIdentifier_QNAME, DCelementType.class, Metadata.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DCelementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.talkbank.org/ns/talkbank", name = "creator", scope = Metadata.class)
    public JAXBElement<DCelementType> createMetadataCreator(DCelementType value) {
        return new JAXBElement<DCelementType>(_MetadataCreator_QNAME, DCelementType.class, Metadata.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DCelementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.talkbank.org/ns/talkbank", name = "subject", scope = Metadata.class)
    public JAXBElement<DCelementType> createMetadataSubject(DCelementType value) {
        return new JAXBElement<DCelementType>(_MetadataSubject_QNAME, DCelementType.class, Metadata.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DCelementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.talkbank.org/ns/talkbank", name = "format", scope = Metadata.class)
    public JAXBElement<DCelementType> createMetadataFormat(DCelementType value) {
        return new JAXBElement<DCelementType>(_MetadataFormat_QNAME, DCelementType.class, Metadata.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DCelementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.talkbank.org/ns/talkbank", name = "description", scope = Metadata.class)
    public JAXBElement<DCelementType> createMetadataDescription(DCelementType value) {
        return new JAXBElement<DCelementType>(_MetadataDescription_QNAME, DCelementType.class, Metadata.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DCelementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.talkbank.org/ns/talkbank", name = "language", scope = Metadata.class)
    public JAXBElement<DCelementType> createMetadataLanguage(DCelementType value) {
        return new JAXBElement<DCelementType>(_MetadataLanguage_QNAME, DCelementType.class, Metadata.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DCelementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.talkbank.org/ns/talkbank", name = "source", scope = Metadata.class)
    public JAXBElement<DCelementType> createMetadataSource(DCelementType value) {
        return new JAXBElement<DCelementType>(_MetadataSource_QNAME, DCelementType.class, Metadata.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DCelementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.talkbank.org/ns/talkbank", name = "title", scope = Metadata.class)
    public JAXBElement<DCelementType> createMetadataTitle(DCelementType value) {
        return new JAXBElement<DCelementType>(_MetadataTitle_QNAME, DCelementType.class, Metadata.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DCelementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.talkbank.org/ns/talkbank", name = "type", scope = Metadata.class)
    public JAXBElement<DCelementType> createMetadataType(DCelementType value) {
        return new JAXBElement<DCelementType>(_MetadataType_QNAME, DCelementType.class, Metadata.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DCelementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.talkbank.org/ns/talkbank", name = "relation", scope = Metadata.class)
    public JAXBElement<DCelementType> createMetadataRelation(DCelementType value) {
        return new JAXBElement<DCelementType>(_MetadataRelation_QNAME, DCelementType.class, Metadata.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DCelementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.talkbank.org/ns/talkbank", name = "contributor", scope = Metadata.class)
    public JAXBElement<DCelementType> createMetadataContributor(DCelementType value) {
        return new JAXBElement<DCelementType>(_MetadataContributor_QNAME, DCelementType.class, Metadata.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DCelementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.talkbank.org/ns/talkbank", name = "rights", scope = Metadata.class)
    public JAXBElement<DCelementType> createMetadataRights(DCelementType value) {
        return new JAXBElement<DCelementType>(_MetadataRights_QNAME, DCelementType.class, Metadata.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DCelementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.talkbank.org/ns/talkbank", name = "appId", scope = Metadata.class)
    public JAXBElement<DCelementType> createMetadataAppId(DCelementType value) {
        return new JAXBElement<DCelementType>(_MetadataAppId_QNAME, DCelementType.class, Metadata.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DCelementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.talkbank.org/ns/talkbank", name = "publisher", scope = Metadata.class)
    public JAXBElement<DCelementType> createMetadataPublisher(DCelementType value) {
        return new JAXBElement<DCelementType>(_MetadataPublisher_QNAME, DCelementType.class, Metadata.class, value);
    }

}
