//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.30 at 05:39:42 PM NZDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.talkbank.org/ns/talkbank", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package talkbank.schema;
