//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.30 at 05:39:42 PM NZDT 
//


package talkbank.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.Duration;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 *                 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;a xmlns="http://www.w3.org/1999/xhtml" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:tb="http://www.talkbank.org/ns/talkbank" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:xs="http://www.w3.org/2001/XMLSchema" href="http://childes.psy.cmu.edu/manuals/chat.html#ID_Header"&gt;
 *                     CHAT manual section on this
 *                     topic...
 *                 &lt;/a&gt;
 * </pre>
 * 
 *             
 * 
 * <p>Java class for participantType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="participantType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="id" use="required" type="{http://www.talkbank.org/ns/talkbank}speakerID" />
 *       &lt;attribute name="role" use="required" type="{http://www.talkbank.org/ns/talkbank}roleType" />
 *       &lt;attribute name="name" type="{http://www.talkbank.org/ns/talkbank}nonemptyStringType" />
 *       &lt;attribute name="age" type="{http://www.w3.org/2001/XMLSchema}duration" />
 *       &lt;attribute name="ageTo" type="{http://www.w3.org/2001/XMLSchema}duration" />
 *       &lt;attribute name="group" type="{http://www.talkbank.org/ns/talkbank}nonemptyStringType" />
 *       &lt;attribute name="sex" type="{http://www.talkbank.org/ns/talkbank}sexType" />
 *       &lt;attribute name="SES" type="{http://www.talkbank.org/ns/talkbank}nonemptyStringType" />
 *       &lt;attribute name="education" type="{http://www.talkbank.org/ns/talkbank}nonemptyStringType" />
 *       &lt;attribute name="custom-field" type="{http://www.talkbank.org/ns/talkbank}nonemptyStringType" />
 *       &lt;attribute name="birthday" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="language" type="{http://www.talkbank.org/ns/talkbank}languagesType" />
 *       &lt;attribute name="first-language" type="{http://www.talkbank.org/ns/talkbank}languageType" />
 *       &lt;attribute name="birthplace" type="{http://www.talkbank.org/ns/talkbank}nonemptyStringType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "participantType")
public class ParticipantType {

    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "role", required = true)
    protected RoleType role;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "age")
    protected Duration age;
    @XmlAttribute(name = "ageTo")
    protected Duration ageTo;
    @XmlAttribute(name = "group")
    protected String group;
    @XmlAttribute(name = "sex")
    protected SexType sex;
    @XmlAttribute(name = "SES")
    protected String ses;
    @XmlAttribute(name = "education")
    protected String education;
    @XmlAttribute(name = "custom-field")
    protected String customField;
    @XmlAttribute(name = "birthday")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar birthday;
    @XmlAttribute(name = "language")
    protected List<String> languages;
    @XmlAttribute(name = "first-language")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String firstLanguage;
    @XmlAttribute(name = "birthplace")
    protected String birthplace;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link RoleType }
     *     
     */
    public RoleType getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoleType }
     *     
     */
    public void setRole(RoleType value) {
        this.role = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the age property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getAge() {
        return age;
    }

    /**
     * Sets the value of the age property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setAge(Duration value) {
        this.age = value;
    }

    /**
     * Gets the value of the ageTo property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getAgeTo() {
        return ageTo;
    }

    /**
     * Sets the value of the ageTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setAgeTo(Duration value) {
        this.ageTo = value;
    }

    /**
     * Gets the value of the group property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroup() {
        return group;
    }

    /**
     * Sets the value of the group property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroup(String value) {
        this.group = value;
    }

    /**
     * Gets the value of the sex property.
     * 
     * @return
     *     possible object is
     *     {@link SexType }
     *     
     */
    public SexType getSex() {
        return sex;
    }

    /**
     * Sets the value of the sex property.
     * 
     * @param value
     *     allowed object is
     *     {@link SexType }
     *     
     */
    public void setSex(SexType value) {
        this.sex = value;
    }

    /**
     * Gets the value of the ses property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSES() {
        return ses;
    }

    /**
     * Sets the value of the ses property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSES(String value) {
        this.ses = value;
    }

    /**
     * Gets the value of the education property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEducation() {
        return education;
    }

    /**
     * Sets the value of the education property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEducation(String value) {
        this.education = value;
    }

    /**
     * Gets the value of the customField property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomField() {
        return customField;
    }

    /**
     * Sets the value of the customField property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomField(String value) {
        this.customField = value;
    }

    /**
     * Gets the value of the birthday property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBirthday() {
        return birthday;
    }

    /**
     * Sets the value of the birthday property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBirthday(XMLGregorianCalendar value) {
        this.birthday = value;
    }

    /**
     * Gets the value of the languages property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the languages property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLanguages().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getLanguages() {
        if (languages == null) {
            languages = new ArrayList<String>();
        }
        return this.languages;
    }

    /**
     * Gets the value of the firstLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstLanguage() {
        return firstLanguage;
    }

    /**
     * Sets the value of the firstLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstLanguage(String value) {
        this.firstLanguage = value;
    }

    /**
     * Gets the value of the birthplace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBirthplace() {
        return birthplace;
    }

    /**
     * Sets the value of the birthplace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBirthplace(String value) {
        this.birthplace = value;
    }

}
