//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.30 at 05:39:42 PM NZDT 
//


package talkbank.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;a xmlns="http://www.w3.org/1999/xhtml" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:tb="http://www.talkbank.org/ns/talkbank" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:xs="http://www.w3.org/2001/XMLSchema" href="http://childes.psy.cmu.edu/manuals/chat.html#Phonological_Group"&gt;
 *                     CHAT manual
 *                     section on this topic...
 *                 &lt;/a&gt;
 * </pre>
 * 
 *             
 * 
 * <p>Java class for phoneticGroupType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="phoneticGroupType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}w"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}g"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}quotation"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}quotation2"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}pause"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}internal-media"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}freecode"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}e"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}s"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}tagMarker"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}long-feature"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}nonvocal"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}overlap-point"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}underline"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}italic"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element ref="{http://www.talkbank.org/ns/talkbank}actual"/>
 *             &lt;element ref="{http://www.talkbank.org/ns/talkbank}model" minOccurs="0"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element ref="{http://www.talkbank.org/ns/talkbank}model"/>
 *             &lt;element ref="{http://www.talkbank.org/ns/talkbank}actual" minOccurs="0"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.talkbank.org/ns/talkbank}align" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "phoneticGroupType", propOrder = {
    "wsAndGSAndQuotations",
    "actualsAndModels",
    "align"
})
@XmlRootElement(name = "pg")
public class Pg {

    @XmlElements({
        @XmlElement(name = "w", type = W.class),
        @XmlElement(name = "g", type = G.class),
        @XmlElement(name = "quotation", type = Quotation.class),
        @XmlElement(name = "quotation2", type = Quotation2 .class),
        @XmlElement(name = "pause", type = Pause.class),
        @XmlElement(name = "internal-media", type = MediaType.class),
        @XmlElement(name = "freecode", type = Freecode.class),
        @XmlElement(name = "e", type = E.class),
        @XmlElement(name = "s", type = S.class),
        @XmlElement(name = "tagMarker", type = TagMarker.class),
        @XmlElement(name = "long-feature", type = LongFeature.class),
        @XmlElement(name = "nonvocal", type = Nonvocal.class),
        @XmlElement(name = "overlap-point", type = OverlapPoint.class),
        @XmlElement(name = "underline", type = Underline.class),
        @XmlElement(name = "italic", type = Italic.class)
    })
    protected List<Object> wsAndGSAndQuotations;
    @XmlElements({
        @XmlElement(name = "actual", type = Actual.class),
        @XmlElement(name = "model", type = Model.class)
    })
    protected List<PhoType> actualsAndModels;
    protected Align align;

    /**
     * Gets the value of the wsAndGSAndQuotations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the wsAndGSAndQuotations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWSAndGSAndQuotations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link W }
     * {@link G }
     * {@link Quotation }
     * {@link Quotation2 }
     * {@link Pause }
     * {@link MediaType }
     * {@link Freecode }
     * {@link E }
     * {@link S }
     * {@link TagMarker }
     * {@link LongFeature }
     * {@link Nonvocal }
     * {@link OverlapPoint }
     * {@link Underline }
     * {@link Italic }
     * 
     * 
     */
    public List<Object> getWSAndGSAndQuotations() {
        if (wsAndGSAndQuotations == null) {
            wsAndGSAndQuotations = new ArrayList<Object>();
        }
        return this.wsAndGSAndQuotations;
    }

    /**
     * Gets the value of the actualsAndModels property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the actualsAndModels property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActualsAndModels().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Actual }
     * {@link Model }
     * 
     * 
     */
    public List<PhoType> getActualsAndModels() {
        if (actualsAndModels == null) {
            actualsAndModels = new ArrayList<PhoType>();
        }
        return this.actualsAndModels;
    }

    /**
     * Gets the value of the align property.
     * 
     * @return
     *     possible object is
     *     {@link Align }
     *     
     */
    public Align getAlign() {
        return align;
    }

    /**
     * Sets the value of the align property.
     * 
     * @param value
     *     allowed object is
     *     {@link Align }
     *     
     */
    public void setAlign(Align value) {
        this.align = value;
    }

}
