//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.30 at 05:39:42 PM NZDT 
//


package talkbank.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;a xmlns="http://www.talkbank.org/ns/talkbank" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:tb="http://www.talkbank.org/ns/talkbank" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:xs="http://www.w3.org/2001/XMLSchema" href="http://childes.psy.cmu.edu/manuals/chat.html#Phonology_Word"&gt;
 *                     CHAT manual section on
 *                     this topic...
 *                 &lt;/a&gt;
 * </pre>
 * 
 *             
 * 
 * <p>Java class for phoneticWordType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="phoneticWordType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{http://www.talkbank.org/ns/talkbank}ss"/>
 *         &lt;element ref="{http://www.talkbank.org/ns/talkbank}wk"/>
 *         &lt;element ref="{http://www.talkbank.org/ns/talkbank}ph"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "phoneticWordType", propOrder = {
    "ssAndWksAndPhs"
})
@XmlRootElement(name = "pw")
public class Pw {

    @XmlElements({
        @XmlElement(name = "ss", type = Ss.class),
        @XmlElement(name = "wk", type = Wk.class),
        @XmlElement(name = "ph", type = Ph.class)
    })
    protected List<Object> ssAndWksAndPhs;

    /**
     * Gets the value of the ssAndWksAndPhs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ssAndWksAndPhs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSsAndWksAndPhs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ss }
     * {@link Wk }
     * {@link Ph }
     * 
     * 
     */
    public List<Object> getSsAndWksAndPhs() {
        if (ssAndWksAndPhs == null) {
            ssAndWksAndPhs = new ArrayList<Object>();
        }
        return this.ssAndWksAndPhs;
    }

}
