//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.30 at 05:39:42 PM NZDT 
//


package talkbank.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 *                 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;a xmlns="http://www.w3.org/1999/xhtml" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:tb="http://www.talkbank.org/ns/talkbank" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:xs="http://www.w3.org/2001/XMLSchema" href="http://childes.psy.cmu.edu/manuals/chat.html#Utterances"&gt;
 *                     CHAT manual section on
 *                     this topic...
 *                 &lt;/a&gt;
 * </pre>
 * 
 *             
 * 
 * <p>Java class for speakerUtteranceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="speakerUtteranceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="linker" type="{http://www.talkbank.org/ns/talkbank}linkerType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}w"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}blob"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}g"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}pg"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}sg"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}quotation"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}quotation2"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}pause"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}internal-media" minOccurs="0"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}freecode"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}e"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}s"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}tagMarker"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}overlap-point"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}underline"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}italic"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}long-feature"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}nonvocal"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.talkbank.org/ns/talkbank}t"/>
 *         &lt;element ref="{http://www.talkbank.org/ns/talkbank}postcode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.talkbank.org/ns/talkbank}media" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}k"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}error"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}r"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}a"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}lang"/>
 *       &lt;attribute name="who" use="required" type="{http://www.talkbank.org/ns/talkbank}speakerID" />
 *       &lt;attribute name="uID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "speakerUtteranceType", propOrder = {
    "linkers",
    "wsAndBlobsAndGS",
    "t",
    "postcodes",
    "media",
    "ksAndErrorsAndRS"
})
@XmlRootElement(name = "u")
public class U {

    @XmlElement(name = "linker")
    protected List<LinkerType> linkers;
    @XmlElements({
        @XmlElement(name = "w", type = W.class),
        @XmlElement(name = "blob", type = Blob.class),
        @XmlElement(name = "g", type = G.class),
        @XmlElement(name = "pg", type = Pg.class),
        @XmlElement(name = "sg", type = Sg.class),
        @XmlElement(name = "quotation", type = Quotation.class),
        @XmlElement(name = "quotation2", type = Quotation2 .class),
        @XmlElement(name = "pause", type = Pause.class),
        @XmlElement(name = "internal-media", type = MediaType.class),
        @XmlElement(name = "freecode", type = Freecode.class),
        @XmlElement(name = "e", type = E.class),
        @XmlElement(name = "s", type = S.class),
        @XmlElement(name = "tagMarker", type = TagMarker.class),
        @XmlElement(name = "overlap-point", type = OverlapPoint.class),
        @XmlElement(name = "underline", type = Underline.class),
        @XmlElement(name = "italic", type = Italic.class),
        @XmlElement(name = "long-feature", type = LongFeature.class),
        @XmlElement(name = "nonvocal", type = Nonvocal.class)
    })
    protected List<Object> wsAndBlobsAndGS;
    @XmlElement(required = true)
    protected T t;
    @XmlElement(name = "postcode")
    protected List<Postcode> postcodes;
    protected MediaType media;
    @XmlElements({
        @XmlElement(name = "k", type = K.class),
        @XmlElement(name = "error", type = String.class),
        @XmlElement(name = "r", type = R.class),
        @XmlElement(name = "a", type = A.class)
    })
    protected List<Object> ksAndErrorsAndRS;
    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
    protected String lang;
    @XmlAttribute(name = "who", required = true)
    protected String who;
    @XmlAttribute(name = "uID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String uid;

    /**
     * Gets the value of the linkers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the linkers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLinkers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LinkerType }
     * 
     * 
     */
    public List<LinkerType> getLinkers() {
        if (linkers == null) {
            linkers = new ArrayList<LinkerType>();
        }
        return this.linkers;
    }

    /**
     * Gets the value of the wsAndBlobsAndGS property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the wsAndBlobsAndGS property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWSAndBlobsAndGS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link W }
     * {@link Blob }
     * {@link G }
     * {@link Pg }
     * {@link Sg }
     * {@link Quotation }
     * {@link Quotation2 }
     * {@link Pause }
     * {@link MediaType }
     * {@link Freecode }
     * {@link E }
     * {@link S }
     * {@link TagMarker }
     * {@link OverlapPoint }
     * {@link Underline }
     * {@link Italic }
     * {@link LongFeature }
     * {@link Nonvocal }
     * 
     * 
     */
    public List<Object> getWSAndBlobsAndGS() {
        if (wsAndBlobsAndGS == null) {
            wsAndBlobsAndGS = new ArrayList<Object>();
        }
        return this.wsAndBlobsAndGS;
    }

    /**
     * Gets the value of the t property.
     * 
     * @return
     *     possible object is
     *     {@link T }
     *     
     */
    public T getT() {
        return t;
    }

    /**
     * Sets the value of the t property.
     * 
     * @param value
     *     allowed object is
     *     {@link T }
     *     
     */
    public void setT(T value) {
        this.t = value;
    }

    /**
     * Gets the value of the postcodes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the postcodes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPostcodes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Postcode }
     * 
     * 
     */
    public List<Postcode> getPostcodes() {
        if (postcodes == null) {
            postcodes = new ArrayList<Postcode>();
        }
        return this.postcodes;
    }

    /**
     * Gets the value of the media property.
     * 
     * @return
     *     possible object is
     *     {@link MediaType }
     *     
     */
    public MediaType getMedia() {
        return media;
    }

    /**
     * Sets the value of the media property.
     * 
     * @param value
     *     allowed object is
     *     {@link MediaType }
     *     
     */
    public void setMedia(MediaType value) {
        this.media = value;
    }

    /**
     * Gets the value of the ksAndErrorsAndRS property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ksAndErrorsAndRS property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKSAndErrorsAndRS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link K }
     * {@link String }
     * {@link R }
     * {@link A }
     * 
     * 
     */
    public List<Object> getKSAndErrorsAndRS() {
        if (ksAndErrorsAndRS == null) {
            ksAndErrorsAndRS = new ArrayList<Object>();
        }
        return this.ksAndErrorsAndRS;
    }

    /**
     * 
     *                     
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;a xmlns="http://www.w3.org/1999/xhtml" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:tb="http://www.talkbank.org/ns/talkbank" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:xs="http://www.w3.org/2001/XMLSchema" href="http://childes.psy.cmu.edu/manuals/chat.html#Language_Precode"&gt;
     *                         CHAT manual
     *                         section on this topic...
     *                     &lt;/a&gt;
     * </pre>
     * 
     *                 
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the who property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWho() {
        return who;
    }

    /**
     * Sets the value of the who property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWho(String value) {
        this.who = value;
    }

    /**
     * Gets the value of the uid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUID() {
        return uid;
    }

    /**
     * Sets the value of the uid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUID(String value) {
        this.uid = value;
    }

}
