//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.30 at 05:39:42 PM NZDT 
//


package talkbank.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;a xmlns="http://www.w3.org/1999/xhtml" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:tb="http://www.talkbank.org/ns/talkbank" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:xs="http://www.w3.org/2001/XMLSchema" href="http://childes.psy.cmu.edu/manuals/chat.html#Linkages"&gt;
 *                     CHAT manual section on this
 *                     topic...
 *                 &lt;/a&gt;
 * </pre>
 * 
 *             
 * 
 * <p>Java class for wordType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="wordType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.talkbank.org/ns/talkbank}langs" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}overlap-point"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}underline"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}italic"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}shortening"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}p"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}long-feature"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}ca-delimiter"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}ca-element"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}wk"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}pos"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}replacement"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}mor"/>
 *           &lt;element ref="{http://www.talkbank.org/ns/talkbank}mk"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="separated-prefix" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="user-special-form" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="formSuffix" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="formType">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="addition"/>
 *             &lt;enumeration value="babbling"/>
 *             &lt;enumeration value="child-invented"/>
 *             &lt;enumeration value="dialect"/>
 *             &lt;enumeration value="family-specific"/>
 *             &lt;enumeration value="filled pause"/>
 *             &lt;enumeration value="filler syllable"/>
 *             &lt;enumeration value="generic"/>
 *             &lt;enumeration value="interjection"/>
 *             &lt;enumeration value="kana"/>
 *             &lt;enumeration value="letter"/>
 *             &lt;enumeration value="neologism"/>
 *             &lt;enumeration value="no voice"/>
 *             &lt;enumeration value="onomatopoeia"/>
 *             &lt;enumeration value="phonology consistent"/>
 *             &lt;enumeration value="proto-morpheme"/>
 *             &lt;enumeration value="quoted metareference"/>
 *             &lt;enumeration value="sign speech"/>
 *             &lt;enumeration value="singing"/>
 *             &lt;enumeration value="signed language"/>
 *             &lt;enumeration value="test"/>
 *             &lt;enumeration value="UNIBET"/>
 *             &lt;enumeration value="words to be excluded"/>
 *             &lt;enumeration value="word play"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="type">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="action"/>
 *             &lt;enumeration value="omission"/>
 *             &lt;enumeration value="ellipsis"/>
 *             &lt;enumeration value="fragment"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="untranscribed">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="unintelligible"/>
 *             &lt;enumeration value="unintelligible-with-pho"/>
 *             &lt;enumeration value="untranscribed"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "wordType", propOrder = {
    "content"
})
@XmlRootElement(name = "w")
public class W {

    @XmlElementRefs({
        @XmlElementRef(name = "ca-delimiter", namespace = "http://www.talkbank.org/ns/talkbank", type = CaDelimiter.class, required = false),
        @XmlElementRef(name = "shortening", namespace = "http://www.talkbank.org/ns/talkbank", type = Shortening.class, required = false),
        @XmlElementRef(name = "mor", namespace = "http://www.talkbank.org/ns/talkbank", type = Mor.class, required = false),
        @XmlElementRef(name = "p", namespace = "http://www.talkbank.org/ns/talkbank", type = P.class, required = false),
        @XmlElementRef(name = "langs", namespace = "http://www.talkbank.org/ns/talkbank", type = Langs.class, required = false),
        @XmlElementRef(name = "replacement", namespace = "http://www.talkbank.org/ns/talkbank", type = Replacement.class, required = false),
        @XmlElementRef(name = "italic", namespace = "http://www.talkbank.org/ns/talkbank", type = Italic.class, required = false),
        @XmlElementRef(name = "wk", namespace = "http://www.talkbank.org/ns/talkbank", type = Wk.class, required = false),
        @XmlElementRef(name = "underline", namespace = "http://www.talkbank.org/ns/talkbank", type = Underline.class, required = false),
        @XmlElementRef(name = "ca-element", namespace = "http://www.talkbank.org/ns/talkbank", type = CaElement.class, required = false),
        @XmlElementRef(name = "mk", namespace = "http://www.talkbank.org/ns/talkbank", type = Mk.class, required = false),
        @XmlElementRef(name = "overlap-point", namespace = "http://www.talkbank.org/ns/talkbank", type = OverlapPoint.class, required = false),
        @XmlElementRef(name = "pos", namespace = "http://www.talkbank.org/ns/talkbank", type = Pos.class, required = false),
        @XmlElementRef(name = "long-feature", namespace = "http://www.talkbank.org/ns/talkbank", type = LongFeature.class, required = false)
    })
    @XmlMixed
    protected List<Object> content;
    @XmlAttribute(name = "separated-prefix")
    protected Boolean separatedPrefix;
    @XmlAttribute(name = "user-special-form")
    protected String userSpecialForm;
    @XmlAttribute(name = "formSuffix")
    protected String formSuffix;
    @XmlAttribute(name = "formType")
    protected String formType;
    @XmlAttribute(name = "type")
    protected String type;
    @XmlAttribute(name = "untranscribed")
    protected String untranscribed;

    /**
     * 
     *                 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;a xmlns="http://www.w3.org/1999/xhtml" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:tb="http://www.talkbank.org/ns/talkbank" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:xs="http://www.w3.org/2001/XMLSchema" href="http://childes.psy.cmu.edu/manuals/chat.html#Linkages"&gt;
     *                     CHAT manual section on this
     *                     topic...
     *                 &lt;/a&gt;
     * </pre>
     * 
     *             Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CaDelimiter }
     * {@link Shortening }
     * {@link Mor }
     * {@link P }
     * {@link Langs }
     * {@link Replacement }
     * {@link Italic }
     * {@link Wk }
     * {@link Underline }
     * {@link CaElement }
     * {@link Mk }
     * {@link String }
     * {@link OverlapPoint }
     * {@link Pos }
     * {@link LongFeature }
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

    /**
     * Gets the value of the separatedPrefix property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSeparatedPrefix() {
        return separatedPrefix;
    }

    /**
     * Sets the value of the separatedPrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSeparatedPrefix(Boolean value) {
        this.separatedPrefix = value;
    }

    /**
     * Gets the value of the userSpecialForm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserSpecialForm() {
        return userSpecialForm;
    }

    /**
     * Sets the value of the userSpecialForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserSpecialForm(String value) {
        this.userSpecialForm = value;
    }

    /**
     * Gets the value of the formSuffix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormSuffix() {
        return formSuffix;
    }

    /**
     * Sets the value of the formSuffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormSuffix(String value) {
        this.formSuffix = value;
    }

    /**
     * Gets the value of the formType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormType() {
        return formType;
    }

    /**
     * Sets the value of the formType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormType(String value) {
        this.formType = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the untranscribed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUntranscribed() {
        return untranscribed;
    }

    /**
     * Sets the value of the untranscribed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUntranscribed(String value) {
        this.untranscribed = value;
    }

}
