//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.12 at 07:39:49 PM NZDT 
//


package agk.chatbot.schema;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Conversation }
     * 
     */
    public Conversation createConversation() {
        return new Conversation();
    }

    /**
     * Create an instance of {@link Conversation.ResponsePair }
     * 
     */
    public Conversation.ResponsePair createConversationResponsePair() {
        return new Conversation.ResponsePair();
    }

    /**
     * Create an instance of {@link Conversation.ResponsePair.Response }
     * 
     */
    public Conversation.ResponsePair.Response createConversationResponsePairResponse() {
        return new Conversation.ResponsePair.Response();
    }

    /**
     * Create an instance of {@link Conversation.ResponsePair.Statement }
     * 
     */
    public Conversation.ResponsePair.Statement createConversationResponsePairStatement() {
        return new Conversation.ResponsePair.Statement();
    }

    /**
     * Create an instance of {@link Conversation.ResponsePair.Response.Word }
     * 
     */
    public Conversation.ResponsePair.Response.Word createConversationResponsePairResponseWord() {
        return new Conversation.ResponsePair.Response.Word();
    }

    /**
     * Create an instance of {@link Conversation.ResponsePair.Statement.Word }
     * 
     */
    public Conversation.ResponsePair.Statement.Word createConversationResponsePairStatementWord() {
        return new Conversation.ResponsePair.Statement.Word();
    }

}
